### ISSUE TITLE
Add Navbar

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#1]
Userstory
As a user, I need a navbar to access all sections of the application

## Subtasks
- [x] Get Familiar with Maui & Blazor
- [x] Setup page routing
- [x] Build Navbar front-end
- [x] Setup Navbar with routing
- [x] Documentation
- [x] Testing
