### ISSUE TITLE
Add Settings View

### ISSUE THREAD

**Issue by JohnParks032** [ChrispyPeaches/FocusFriends#10]
Userstory
 As a user, I have a settings screen that I can interact with

## Subtasks
- [ ] Get Familiar with Tech Stack
- [ ] Research front-end development
- [ ] Create view
- [ ] Create text components within view
- [ ] Create and link buttons to go to proper screens
- [ ] Document
