### ISSUE TITLE
Add Badge Functionality

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#101]
## Problem
As a user, I have the ability to earn badges

## Definition of Done
- User can earn session badges on focus session end
- User can earn session badges on break session end
- User can earn shopping badges when purchasing item
- User can earn social badge when adding a friend
- User is prompted with popup when earning a badge
- popup prompts user to equip badge

## Subtasks
**Chris**
- [x] Add userbadge endpoint to API
- [x] Add Focus Session badge method to Badge Service
- [x] Add break session badge method to Badge Service
- [x] Add social badge method to badge service

**Evan**
- [x] Add Badge service
- [x] Add purchasing items method to badge service
- [x] Add badge earned popup
