### ISSUE TITLE
Add User Badges Page

### ISSUE THREAD

**Issue by JohnParks032** [ChrispyPeaches/FocusFriends#107]
## Problem
As a user, I am able to see and select which badge I want to display.

## Definition of Done
- Badges are shown from local db which is already synced with api
- Only badges owned by the user are selectable
- Visually differentiate between locked and unlocked

## Subtasks
- [x] Create Badge icons
- [x] Create Badge sync with local and cloud db
- [x] Create db query for the UserBadge collection
- [x] Create front end page to showcase all owned and unowned badges
