### ISSUE TITLE
Add Persistent Login

### ISSUE THREAD

**Issue by iggy808** [ChrispyPeaches/FocusFriends#113]
## Problem
As a user, I'd would like to avoid the sign in process every time i start the application.

### Definition of Done
- After logging in, user's identity token is stored in secure storage
- On app startup, the secure storage is checked for the user's token, validated if present, and used to log the user in
- User does not have to log back into the app every time the application starts

## Subtasks
- [x] Add UserManager singleton to project for fetching and validating tokens from secure storage
- [x] Add user tokens to secure storage on successful login
- [x] Remove user tokens from secure storage when user logs out
