### ISSUE TITLE
Update Persistent Login To Handle Expiring Tokens / Refresh Tokens

### ISSUE THREAD

**Issue by iggy808** [ChrispyPeaches/FocusFriends#115]
## Problem
As a user, I would like my token to be refreshed upon expiration so that I do not have to log in again.

## Definition of Done
- Authentication token expiration is handled automatically
- Token is refreshed after token expires

## Subtasks
- [ ] Research how expired tokens work
- [ ] Research refresh tokens
- [ ] After research, finish task list and implement solution

**Comment by ChrispyPeaches** [comment]
Completed
