### ISSUE TITLE
Add Social View

### ISSUE THREAD

**Issue by wesleypayton** [ChrispyPeaches/FocusFriends#2]
As a user, I can view a social screen that contains my friends

## Subtasks

- [x] Get familiar with tech stack
- [x] Create new view
- [x] Create header
- [x] Create placeholders for friends
- [x] Link navbar button to view
- [ ] Document
