### ISSUE TITLE
Add Adjustable Timer to Timer screen

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#27]
**Userstory**
As a user, I need adjustable timer that switches between focus and break modes

## Subtasks
- [x] Add interface for increasing & decreasing timer length
- [x] Add functionality for timer to decrease over time
- [x] Add switching between focus and break timers
- [x] Add ability to skip break timer
- [x] Documentation & Testing
