### ISSUE TITLE
Add Island

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#28]
**Userstory**
As a user, I need a motivating island to help with getting my work done

### Subtasks
- [x] Plan design for island
- [x] Create graphics for initial island
- [x] Add a modular container for displaying different islands
- [x] Add a modular container for displaying different pets on the island
- [x] Documentation & Testing
