### ISSUE TITLE
Implement slide animation between tabs on the navbar

### ISSUE THREAD

**Issue by wesleypayton** [ChrispyPeaches/FocusFriends#3]
As a user, I see a slide animation between pages when hitting buttons on the navbar

## Subtasks

- [x] Research mobile view animations
- [x] Create snazzy left and right swipe animation
- [x] Implement in researched way that makes sense
- [ ] Document

**Comment by wesleypayton** [comment]
This feature is being moved to the backlog as potential implementations are either not compatible with our solution or will require lots of refactoring of how our current views function.

Moving this to the backlog for a future sprint to tackle.

This was the most promising I could find but it may not function properly with how our views are set up:
https://stackoverflow.com/questions/74973199/net-maui-navigation-animation

**Comment by ChrispyPeaches** [comment]
Just some notes that might help when this story is picked up:

I think Sharpnado has something built in for making custom animations. 
- It’s demonstrated at the bottom of the readme for tabs, but it might be applicable to views.
    https://github.com/roubachof/Sharpnado.Tabs/tree/main?tab=readme-ov-file#custom-spam-tabs-
- And here it is in the sample Sharpnado app
 
 
 
 https://github.com/roubachof/Sharpnado.Tabs/blob/e8dc4e2446e510797a334a1c66f3b397361027fc/MauiSample/Presentation/CustomViews/SpamTab.xaml.cs#L73

It's also possible that the animation shown is a built-in part of the android platform. I dealt with a built-in animation like this and it was called TouchEffect. This animation might have a similar origin
