### ISSUE TITLE
Add database to FocusApp

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#39]
## Problem
As a developer, I need a database in the app to store users' local data

## Solution
Add a SQLite database to the FocusApp project

## Definition of Done
The user can log a session in the app's database.

## Subtasks
- [x] Setup entity framework on the FocusApp
- [x] Standardize entity framework between projects
- [x] Setup FocusAPI to work with standardization
- [x] Add migrations to the FocusApp database
- [x] Setup local database to log session
- [x] Documentation & Testing
