### ISSUE TITLE
Setup CI/CD Flow

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#4]
As a developer, I need a CI/CD flow for deployment and testing

## Subtasks
- [x] Get Familiar with Github Actions
- [x] Documentation
- [x] Testing

#### CI
- [x] Setup build status checks for FocusAPI and FocusApp
- [x] Setup a flow for verifying the apps builds when reviewing pull requests

#### CD
- [x] Get Familiar with Docker & Portainer
- [x] Setup a flow for deploying the API to a test environment
