### ISSUE TITLE
Add Login Page

### ISSUE THREAD

**Issue by JohnParks032** [ChrispyPeaches/FocusFriends#41]
Userstory
As a user, I need a login screen to be able to sign in

## Subtasks
- [ ] Create login page
- [ ] Implement Google SSO Auth via button redirect
- [ ] Create and link buttons to go to proper pages
- [ ] Document

## Definition of Done
Have a skippable login screen on app startup with ability to login via SSO. Additional button to go back to login if skipped.
