### ISSUE TITLE
Add Session Ratings with Mindfulness Tips and Tips on Startup

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#51]
## Problem
As a user, I can rate my session and get a mindfulness tip based on my rating and a tip when I start the app

## Solution
- Add a mindfulness tip template popup interface
- Add mindfulness tips to the FocusApp and FocusAPI database schemas
- Add a popup interface for the user to rate their focus session
    - Show the popup when a focus session is completed
    - Show the user a mindfulness tip based on their rating

## Definition of Done
- The user has a mindfulness tip pop up when the timer page is shown on startup
- The user has a prompt to rate their focus session on a successful completion
- When the user rates their focus session, theyre shown a random mindfulness tip correlating to their session rating
- The mindfulness tip popup is a template that shows content from a database entry for the tip

## Subtasks
- [x] Add mindfulness tips to API and Mobile databases
- [x] Setup app to fetch tips from API
- [x] Create mindfulness popup
- [x] Create and integrate session rating popup
- [x] integrate popup to show on app start
- [x] Create setting for popup on startup (boolean at first)
- [x] Documentation and Testing
