### ISSUE TITLE
User Preferences

### ISSUE THREAD

**Issue by JohnParks032** [ChrispyPeaches/FocusFriends#53]
## Problem
As a user, I can have my settings saved and reloaded when I open the app

## Definition of Done
- The user has access to a feature rich setting menu
- Default settings are added and saved to .NET MAUI preferences 
- Settings can be saved according to the changed made by the user

## Subtasks
- [x] Research .NET MAUI Preferences
- [x] Implement preferences to save settings according to user
- [x] Connect frontend UI to any backend necessary
- [x] Documentation & Testing
