### ISSUE TITLE
Rework Focus API to deploy under https instead of http

### ISSUE THREAD

**Issue by wesleypayton** [ChrispyPeaches/FocusFriends#54]
## Problem
As a developer, I need the focus app and api to deploy under https rather than http

## Definition of Done
- Focus API can be deployed locally using https and the app can communicate with it without issue

## Subtasks
- [ ] Research changing to https authentication
- [ ] Make change to focus app according to research
- [ ] Make change to focus api according to research
- [ ] Documentation and Testing
