### ISSUE TITLE
Add new friend functionality

### ISSUE THREAD

**Issue by wesleypayton** [ChrispyPeaches/FocusFriends#55]
## Problem
As a user, I am able to add friends via a button and entry on the social page

## Definition of Done
- A new button for adding friends is available on the social screen
- User can add a friend by entering their (could be email, code, username, TBD) into an entry accessed via new button
- User and friend relationship is created in database
- Friends are fetched and populated into friends list on social page
- Username is fetched in profile interface popup

## Subtasks
- [x] Research methods of adding friends (email, username, code)
- [x] Implement method of adding friends to database if needed
- [x] Create button on social page for adding friends
- [x] Implement API call to adding a friend
- [x] Tie button/entry and api call together
- [x] Documentation and Testing
