### ISSUE TITLE
Add ability to change equipped pet

### ISSUE THREAD

**Issue by wesleypayton** [ChrispyPeaches/FocusFriends#56]
## Problem
As a user, I am able to change what pet I have on my island by selecting a different pet on the pets page

## Definition of Done
- User can navigate to pets page and tap a pet they have unlocked to equip that pet
- User's currently equipped pet is the pet that is displayed on their island

## Subtasks
- [ ] Examine how pets are currently handled by timer page, pets page, and database
- [ ] Implement functionality to update database when user selects a different pet
- [ ] Add logic to timer page to display pets according to what user has equipped
- [ ] Documentation and Testing
