### ISSUE TITLE
User Sounds

### ISSUE THREAD

**Issue by JohnParks032** [ChrispyPeaches/FocusFriends#61]
## Problem
As a user, I need mindful audio and ambience to play throughout the app

## Definition of Done
- Ambient audio plays throughout the app
- Audio volume can be adjusted by the user settings

## Subtasks
- [x] Research placeholder mindful audio and ambiance
- [ ] Create any necessary audio interfaces
- [ ] Connect audio interface to settings
- [ ] Implement audio adjustable by settings
- [ ] Documentation and settings
