### ISSUE TITLE
Integrate User Session Storage

### ISSUE THREAD

**Issue by iggy808** [ChrispyPeaches/FocusFriends#65]
## Problem
After timer session is completed, the session is not recorded under the currently logged in user.

## Definition of Done
After a timer session, the UserSessions table on the local database and the server database are updated accordingly.

## Subtasks
- [x] Retrieve currently logged in user details from local database upon timer session finish
- [x] Store UserSession data within local context
- [x] Create API endpoint for posting UserSession data to the server database
- [x] After timer session finish, call newly created API endpoint to store UserSession data on server database
- [x] Update user's currency to add the currency earned from the session
