### ISSUE TITLE
Implement Leaderboard Backend/Frontend

### ISSUE THREAD

**Issue by iggy808** [ChrispyPeaches/FocusFriends#66]
## Problem
As a user, I would like to see a leaderboard of my friend's study session stats. Additionally, I would like to be able to view these stats within a daily or weekly timeframe.

## Definition of Done
I can navigate to the leaderboards screen, and I can view daily/weekly leaderboards of my friends' stats.

## Subtasks
- [ ] Create UI buttons for Daily / Weekly leaderboards
- [ ] Create UI for showing top 3 friends on the leaderboard
- [ ] Create UI for scrolling through friends that are not in the top 3
- [ ] Create API endpoint for fetching Daily friend session stats
- [ ] Create DTO that includes friend data as well as aggregated session data
- [ ] On the server, aggregate daily friend session stats, and return DTO for friend / their aggregated session stats
- [ ] On Daily leaderboard page load, call Daily friend session stats endpoint for leaderboard data
- [ ] Populate UI with friend session stats
- [ ] Create API endpoint for fetching Weekly friend session stats
- [ ] On the server, aggregate weekly friend session stats, and return DTO for friend / their aggregated session stats
- [ ] On Weekly leaderboard page load, call Weekly friend session stats endpoint for leaderboard data
