### ISSUE TITLE
Add custom control for displaying the island

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#67]
## Problem
As a developer, I need to have a custom control for showing my island that I can use on multiple pages and that can show the currently selected pet, decor, etc.

## Definition of Done
- Currently selected pet, decor, badge, and decor is stored in authentication service, mobile db, and API db 
- Custom control is usable anywhere in the application
- Custom control is usable if user is not logged in

## Subtasks
- [x] Extract island page into a custom control
- [x] Setup backend to attach pet and island to new users
- [x] Create columns in db for user selected pet, sound, etc.
- [x] Add display decor to island
- [x] Include the selected pet, and decor in the displayed island
- [x] Setup sync to grab initial pet and island if they don't exist in the database
- [x] Make display of pet on island more dynamic
- [ ] Documentation and testing
