### ISSUE TITLE
Integrate user sessions into local and server backend

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#68]
## Problem
As a developer, I need to integrate the user session completion with the local and server backend

## Definition of Done
- After a timer session,  the UserSessions table on the local database and the server database are updated accordingly.

## Subtasks
- [ ] Retrieve currently logged in user details from local database upon timer session finish
- [ ] Store UserSession data within local context
- [ ] Create API endpoint for posting UserSession data to the server database
- [ ] After timer session finish, call newly created API endpoint to store UserSession data on server database

**Comment by ChrispyPeaches** [comment]
Duplicate of #65
