### ISSUE TITLE
Add Friend Profile Details Page

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#69]
## Problem
As a user, I can view my friends' islands and see their profile info and what island additions they have equipped

## Definition of Done
- User can select friend profile and be move to a page
- That page will have the user's current badge, island, and pet, and profile info
- Those details are displayed at the top
- Tab bar is not displayed

## Subtasks
- [ ] Create page to display profile details and island additions
- [ ] Add profile details on page
- [ ] Add island display control to page
- [ ] Setup back button to lead to last page
- [ ] Setup buttons on social screen to lead to details page when clicked
