### ISSUE TITLE
Add Decor/Furniture Page

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#71]
## Problem
As a user, I want to view and select decor on my island

## Definition of Done
- selected decor is displayed on the island
- user can choose whether or not to display a decor item
- User does not initially get furniture. They have to buy it
- Add decor page where user can view all unlocked decor and select one to be displayed on island

## Subtasks
- [ ] Create decor page
- [ ] Setup page to use styling template from badges page
- [ ] Setup page to find which decor items user the user has unlocked
- [ ] Setup page to display those decor items that are unlocked
- [ ] Setup page to show selected decor item
- [ ] Setup page to allow user to select a decor item
- [ ] Documentation and Testing
