### ISSUE TITLE
Fix Pets Page

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#72]
## Problem
As a user, I'm able to see all of my pets in the pets page  and select a pet from the ones I own

## Definition of Done
- Dynamic generation of pets page with pet display template
- See and set which pet is selected for the current user

## Subtasks
- [x] Research
- [x] Rework current pets page to query from local (Dynamic pets)
- [x] Implement functionality to update databases and auth service when user selects a different pet
- [ ] Documentation and Testing
