### ISSUE TITLE
Add Islands Page

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#73]
## Problem
As a user, I want the ability to view my owned islands and select a different one

## Definition of Done
- Island Page is added
- Dynamic generation of Island page with Island display template
- See which is selected
- Set which is selected

## Subtasks
- [ ] Research
- [ ] Create island page with dynamically generated island displays
- [ ] Implement functionality to update databases and auth service when user selects a different pet
- [ ] Documentation and Testing
