### ISSUE TITLE
Update ShopUI to have Scrolling Functionality

### ISSUE THREAD

**Issue by iggy808** [ChrispyPeaches/FocusFriends#81]
## Problem
As a user, I would like to be able to view carousels that are further down on the shop screen than the initial three carousels.

## Definition of Done

The user can scroll down the shop interface to view additional shop carousels.

## Subtasks
- [ ] Change the stack view to a MAUI view that allows for scrolling
- [ ] Insert shop item carousels into the new scroll view
- [ ] Ensure users are able to scroll down the Shop UI and see carousels that are initially out of range
- [ ] Documentation and Testing
