### ISSUE TITLE
Implement Friend Status Indicators on Social Page

### ISSUE THREAD

**Issue by iggy808** [ChrispyPeaches/FocusFriends#83]
## Problem
As a user, I want to know when my friends are online, offline, or focusing.

## Definition of Done
- When on the social page, I can see which of my friends are online, offline, or focusing.

## Subtasks
- [ ] Research WebSockets, determine how this can be used to retrieve friend statuses
- [ ] Implement the new technology required to share with friends whether a user is in an active session or not
- [ ] Update the UI to display whether or not a friend is online or offline
- [ ] Documentation and Testing
