### ISSUE TITLE
Sprint 4 Bug Fixes

### ISSUE THREAD

**Issue by iggy808** [ChrispyPeaches/FocusFriends#85]
## Problem
Fixing up loose ends from Sprint 4

## Definition of Done
- User is added to local database on sign in if not already there
- App no longer crashes when popup service attempts to access disposed popup
- Make app more reliable
- Make app give helpful logs

## Subtasks
- [x] Add user to local database on sign in if not already there
- [x] Prevent users from dismissing popups via clicking outside of the box
- [x] Add try/catches to API calls
- [x] Add logs to pages, log when API calls fail
