### ISSUE TITLE
Sync all user selectable items on app startup

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#91]
## Problem
As a developer, I need to ensure that all user-selectable items are available when using the application

## Definition of Done
Badges, Tips, Islands, Decor, and Pets are synced with the API on app startup

## Subtasks
- [x] Standardize sync logic for generic type
- [x] Create Badges sync
- [x] Create Islands sync
- [x] Create Decor sync
- [x] Create Pets sync
- [x] Create Tips sync to work with new standardization
- [x] Documentation and Testing
