### ISSUE TITLE
Add Islands To Shop / Refactor Shop Logic

### ISSUE THREAD

**Issue by iggy808** [ChrispyPeaches/FocusFriends#97]
## Problem
As a user I would like to be able to buy islands from the shop.

## Definition of Done
- Shop screen has an island carousel with the "Islands" label
- User can purchase islands from the shop
  - Purchased islands are stored on the server and the local db

## Subtasks
- [x] Update carousel label to read "Islands" instead of "Sounds"
- [x] Add 7 purchasable islands to test database
- [x] Populate island carousel with islands from local database
- [x] Remove logic saving islands to local context upon item purchase
- [x] Make shop methods async where possible
- [x] Refactor error logging to catch entire exception and custom message
